### ISSUE TITLE
[works-input] title과 placeholder값이 같이 있는 경우 화면 오류 발생

### ISSUE THREAD

**Issue by dongz-igaw** [IGAWorksDev/homeworks#2]
## works-input 에서 title과 placeholder값이 같이 있는 경우 화면 오류 발생

```
[] bug reporting
[] feature request
[] support request
[] other
```

### works-input 에서 title과 placeholder값이 같이 있는 경우 화면 오류 발생 합니다.

![image](https://cloud.githubusercontent.com/assets/11733360/24236836/edb33108-0fe6-11e7-932c-95d559c4cbb8.png)

```
<works-input color="normal"
	 size="large"
	 block
	 type="text"
	 id="name"
	 name="name"
	 title="Schedule Name"
	 required="true"
	 validation="true"
	 placeholder="관리용 이름을 넣어주세요."
	 value="name">
</works-input>
```

**Solution Version**

 - v1.0.0
 
**Requester**

 - Kenneth

**Browser**

 - Chrome

**Error found date**

 - 2017-01-01 00:00 AM

**Comment by kenneth-igaw** [comment]
이슈리포팅 감사합니다 해당 이슈는 현재 Homeworks `v1.0.7`에서도 발생할 것으로 예상됩니다.

다음 버전인 v1.0.8에서 해결 될 예정입니다.

**Comment by kenneth-igaw** [comment]
https://github.com/IGAWorksDev/homeworks/commit/18f986ebc39fcf45272f49a7385138bbe15599e5#comments

위 안내와 같이

title과 placeholder를 같은 속성처럼 지원하려고 하는 호환 코드의 문제로 파악됩니다.

이 부분은 title은 placeholder에 관여하지 않도록 조정하여 해결하였습니다.

**Comment by kenneth-igaw** [comment]
해당 이슈는 해결이 되어 `종료`합니다.

다른 이슈가 있으면 새 이슈를 이용해주세요. 🍺

**Comment by kenneth-igaw** [comment]
앞으로는 체크박스에 해당하는 부분에 `x` 표기 부탁드립니다.

EX) 지금의 경우에는

```
[x] bug reporting
[] feature request
[] support request
[] other
```

이렇게 체크하시면 됩니다.
